services:
  db:
    image: mysql/mysql-server:8.0.23
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: lifts
      MYSQL_USER: lift
      MYSQL_PASSWORD: lift1234@
    expose:
      - '3306'


  app:
    container_name: api-lifts
    build: .
    ports: 
      - 8090:8090 
    restart: on-failure
    environment:
      MYSQL_DATABASE: lifts
      MYSQL_HOST: db:3306
      MYSQL_USER: lift
      MYSQL_PASSWORD: lift1234@
    depends_on:
      - db          

