
version: '3'
services:
  app:
    container_name: api-lifts
    build: .
    ports: 
      - 8090:8090 
    restart: on-failure
    environment:
      MYSQL_DATABASE: lifts
      MYSQL_HOST: localhost:3306 
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
    depends_on:
      - mysql          


  mysql:
    image: mysql:5.7
    container_name: mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE: lifts
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
